apiVersion: aim.silogen.ai/v1alpha1
kind: AIMModelCache
metadata:
  name: llama-3-3-70b-cache
  namespace: default
spec:
  runtimeConfigName: amd-aim-cluster-runtime-config
  size: 70Gi
  sourceUri: hf://amd/Llama-3.3-70B-Instruct-FP8-KV
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMModelCache
metadata:
  name: mixtral-8x22b-cache
  namespace: default
spec:
  runtimeConfigName: amd-aim-cluster-runtime-config
  size: 280Gi
  sourceUri: hf://mistralai/Mixtral-8x22B-Instruct-v0.1
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMModelCache
metadata:
  name: openai-gpt-oss-120b
  namespace: default
spec:
  runtimeConfigName: default
  size: 240Gi
  sourceUri: hf://openai/gpt-oss-120b
  modelDownloadImage: gpt-oss-downloader:hf-transfer

